//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAO_SV_NOHP
    {
        public string MaHKNH { get; set; }
        public string MaSinhVien { get; set; }
        public Nullable<decimal> SoTienConLai { get; set; }
    
        public virtual HKNH HKNH { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
