//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_NGANH
    {
        public string MaNganh { get; set; }
        public string MaMonHoc { get; set; }
        public int HocKy { get; set; }
    
        public virtual MONHOC MONHOC { get; set; }
        public virtual NGANH NGANH { get; set; }
    }
}
