//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CT_NGANH
    {
        [Required(ErrorMessage = "Cần nhập mã ngành")]
        public string MaNganh { get; set; }

        [Required(ErrorMessage = "Cần nhập mã môn học")]
        public string MaMonHoc { get; set; }

        [Required(ErrorMessage = "Cần nhập học kỳ")]
        public int HocKy { get; set; }

        public virtual MONHOC MONHOC { get; set; }
        public virtual NGANH NGANH { get; set; }
    }
}
