//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;

    public partial class CT_PHIEUDK
    {
        public string SoPhieuDK { get; set; }
        public string MaMo { get; set; }
        public string GhiChu { get; set; }

        public virtual DS_MONHOC_MO DS_MONHOC_MO { get; set; }
        public virtual PHIEU_DK PHIEU_DK { get; set; }
    }
}
