//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DOITUONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOITUONG()
        {
            this.SINHVIENs = new HashSet<SINHVIEN>();
        }

        [Required(ErrorMessage = "Cần nhập mã đối tượng")]
        public string MaDoiTuong { get; set; }

        [Required(ErrorMessage = "Cần nhập tên đối tượng")]
        public string TenDoiTuong { get; set; }

        [Required(ErrorMessage = "Cần nhập tỉ lệ giảm học phí")]
        public Nullable<int> TiLeGiamHocPhi { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SINHVIEN> SINHVIENs { get; set; }
    }
}
