//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;

    public partial class DS_MONHOC_MO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DS_MONHOC_MO()
        {
            this.CT_PHIEUDK = new HashSet<CT_PHIEUDK>();
        }

        public string MaMo { get; set; }
        public string MaHKNH { get; set; }
        public string MaMonHoc { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUDK> CT_PHIEUDK { get; set; }
        public virtual HKNH HKNH { get; set; }
        public virtual MONHOC MONHOC { get; set; }
    }
}
