//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HKNH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HKNH()
        {
            this.BAOCAO_SV_NOHP = new HashSet<BAOCAO_SV_NOHP>();
            this.DS_MONHOC_MO = new HashSet<DS_MONHOC_MO>();
            this.PHIEU_DK = new HashSet<PHIEU_DK>();
        }

        [Required(ErrorMessage = "Cần nhập mã HKNH")]
        public string MaHKNH { get; set; }

        [Required(ErrorMessage = "Cần nhập học kỳ")]
        public string HocKy { get; set; }

        [Required(ErrorMessage = "Cần nhập năm học")]
        public Nullable<int> Nam1 { get; set; }

        [Required(ErrorMessage = "Cần nhập năm học")]
        public Nullable<int> Nam2 { get; set; }

        [Required(ErrorMessage = "Cần nhập ngày hết hạn")]
        [DataType(DataType.Date)] //Hỗ trợ nhập kiểu ngày
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)] //Dùng để hiển thị
        public Nullable<System.DateTime> HanDongHocPhi { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAO_SV_NOHP> BAOCAO_SV_NOHP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DS_MONHOC_MO> DS_MONHOC_MO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_DK> PHIEU_DK { get; set; }
    }
}
