//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HUYEN()
        {
            this.SINHVIENs = new HashSet<SINHVIEN>();
        }

        [Required(ErrorMessage = "Cần nhập mã huyện")]
        public string MaHuyen { get; set; }

        [Required(ErrorMessage = "Cần nhập tên huyện")]
        public string TenHuyen { get; set; }

        [Required(ErrorMessage = "Cần chọn tỉnh")]
        public string MaTinh { get; set; }

        [Required(ErrorMessage = "Chưa chọn")]
        public Nullable<bool> UuTien { get; set; }

        public virtual TINH TINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SINHVIEN> SINHVIENs { get; set; }
    }
}
