//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LOAIMON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIMON()
        {
            this.MONHOCs = new HashSet<MONHOC>();
        }
        [Required(ErrorMessage = "Cần nhập mã loại môn")]
        public string MaLoaiMon { get; set; }
        public string TenLoaiMon { get; set; }

        [Required(ErrorMessage = "Cần nhập số tiết/tín chỉ")]
        public Nullable<int> SoTietTC { get; set; }

        [Required(ErrorMessage = "Cần nhập số tiền/tín chỉ")]
        public Nullable<decimal> SoTienTC { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MONHOC> MONHOCs { get; set; }
    }
}
