//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANQUYEN
    {
        public int ID { get; set; }
        public int IDTaiKhoan { get; set; }
        public int IDNhomNguoiDung { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual NHOMNGUOIDUNG NHOMNGUOIDUNG { get; set; }
    }
}
