//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PHIEUTHU
    {
        public string SoPhieuThu { get; set; }
        public string SoPhieuDK { get; set; }
        [DataType(DataType.Date)] //Hỗ trợ nhập kiểu ngày
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)] //Dùng để hiển thị
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<decimal> SoTienThu { get; set; }

        public virtual PHIEU_DK PHIEU_DK { get; set; }
    }
}
