//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PHIEU_DK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEU_DK()
        {
            this.CT_PHIEUDK = new HashSet<CT_PHIEUDK>();
            this.PHIEUTHUs = new HashSet<PHIEUTHU>();
            SoTienDangKy = 0;
            SoTienPhaiDong = 0;
            SoTienDaDong = 0;
            SoTienConLai = 0;
        }

        public string SoPhieuDK { get; set; }
        public string MaSinhVien { get; set; }

        [DataType(DataType.Date)] //Hỗ trợ nhập kiểu ngày
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)] //Dùng để hiển thị
        public Nullable<System.DateTime> NgayDK { get; set; }
        public string MaHKNH { get; set; }
        public Nullable<decimal> SoTienDangKy { get; set; }
        public Nullable<decimal> SoTienPhaiDong { get; set; }
        public Nullable<decimal> SoTienDaDong { get; set; }
        public Nullable<decimal> SoTienConLai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUDK> CT_PHIEUDK { get; set; }
        public virtual HKNH HKNH { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTHU> PHIEUTHUs { get; set; }
    }
}
