//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class SINHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SINHVIEN()
        {
            this.BAOCAO_SV_NOHP = new HashSet<BAOCAO_SV_NOHP>();
            this.PHIEU_DK = new HashSet<PHIEU_DK>();
        }
        [Required(ErrorMessage = "Cần nhập mã sinh viên")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Mã sinh viên phải là số")]
        [MinLength(4, ErrorMessage = "Mã sinh viên phải có 4 ký tự")]
        [Index("Ix_MaSinhVien", Order = 1, IsUnique = false)]
        //[Index("Ix_MaSinhVien", Order = 1)]
        public string MaSinhVien { get; set; }

        [Required(ErrorMessage = "Cần nhập tên sinh viên")]
        public string HoTen { get; set; }

        public string GioiTinh { get; set; }

        [Required(ErrorMessage = "Cần nhập ngày sinh")]
        [DataType(DataType.Date)] //Hỗ trợ nhập kiểu ngày
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)] //Dùng để hiển thị
        public System.DateTime NgaySinh { get; set; }

        [Required(ErrorMessage = "Cần chọn huyện")]
        public string MaHuyen { get; set; }

        //[Required(ErrorMessage = "Cần chọn tỉnh")]
        public string MaTinh { get; set; }

        [Required(ErrorMessage = "Cần chọn đối tượng")]
        public string MaDoiTuong { get; set; }

        [Required(ErrorMessage = "Cần chọn ngành")]
        public string MaNganh { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAO_SV_NOHP> BAOCAO_SV_NOHP { get; set; }
        public virtual DOITUONG DOITUONG { get; set; }
        public virtual HUYEN HUYEN { get; set; }
        public virtual TINH TINH { get; set; }
        public virtual NGANH NGANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_DK> PHIEU_DK { get; set; }
    }
}
